spring.application.name=contactos
# Conexion a mysql
spring.datasource.url=${URL}
spring.datasource.username=${USER_NAME}
spring.datasource.password=${PASSWORD_DB}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#Disminuir la informacion proporcionada en la consola
logging.level.root=INFO
logging.level.gm.contactos=INFO
logging.level.org.hibernate=WARN
logging.pattern.console=[%thread] %-5level: %logger{36} - %msg%n

# Banner Spring
spring.main.banner-mode=off

#Propiedades de Thymeleaf
#Lee la plantilla en cada peticion para que los cambios se vean inmediatamenmte
spring.thymeleaf.cache=false